version: '3.1'

services:
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    volumes:
      - /Users/Shared/data/db:/data/db
  backend:
    container_name: backend
    image: 'praca-inzynierska-backend:latest'
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
  admin:
    container_name: admin
    image: 'praca-inzynierska-admin:latest'
    ports:
      - 8081:80
